
baseURL = "https://jmkettle.com/"
title = "James Kettle"
languageCode = "en-us"

[params]
  author = "James Kettle"
  description = "Personal website of James Kettle"

[markup.goldmark.renderer]
  unsafe = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Writing"
    url = "/writing/"
    weight = 2
  [[menu.main]]
    name = "Photos"
    url = "/photos/"
    weight = 3
  [[menu.main]]
    name = "Music"
    url = "/music/"
    weight = 4
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5