
baseURL = "https://jmkettle.com/"
title = "j.m. kettle"
languageCode = "en-us"

[params]
  author = "j.m. kettle"
  description = "Personal website of j.m. kettle"

[markup.goldmark.renderer]
  unsafe = true

[taxonomies]
  category = "categories"
  writing_category = "writing_categories"
  music_category = "music_categories"
  genre = "genres"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Writing"
    url = "/writing/"
    weight = 2
  [[menu.main]]
    name = "Photos"
    url = "/photos/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5